name: check_filename
on: [push, pull_request]
jobs:
  check_hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sha1sum collection/* | \
          perl -nle '
            /^(\w{64})  (collection\/(.+)_(.+)\.\w+)$/;  
            if (lc($1) ne lc($4)) {
              print "FAIL: $2 : sha1sum should be $1!";
              $err = 1;
            };
            END {
              exit 1 if $err == 1
            }'